[package]
name = "host"
version = "0.1.0"
authors = ["tatmanblue <Matt.Raffel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.1"
tide = "0.1.0"
serde = "1.0.80"
serde_derive = "1.0.80"