version: 2.1

orbs:
  rust: circleci/rust@1.1.0
  
  
jobs:
  build:
    executor: rust/default   
    steps:
        - checkout
        - run:
            name: building host
            command: |
                cd host
                cargo build
        - run:
            name: running shared tests
            command: |
              cd shared
              cargo test
