name: rust-aries-host
version: "1.0"
about: configuration for rust-aries-agent host app
author: tatmanblue <Matt.Raffel@gmail.com>

# AppSettings can be defined as a list and are **not** ascii case sensitive
settings:
  - ArgRequiredElseHelp

# All Args must be defined in the 'args:' list where the name of the arg, is the
# key to a Hash object
#
# toThink():
#  1 as this list grows it might be easier to have the app initialize from
#    a json or yaml config file.
args:
  - host:
      help: ip/port host will use to listen to request such as 127.0.0.1:8000
      short: h
      long: host
      takes_value: true
  - role:
      help: describes overall behavior of app.  Either acting as an agent or agency.
      short: r
      long: role
      takes_value: true
      possible_values:
          - agent
          - agency
  - walletType:
      help: wallet storage for agent. Basic is file based and indy is using indy-sdk wallets. Defaults to basic
      short: w
      long: wallet-type
      takes_value: true
      possible_values:
        - basic
        - indy
  - walletConfig:
      help: input for configuring wallet. see docs for details.  its likely to be json format specific for type
      short: c
      long: wallet-config
      takes_value: true
  - automation:
      help: (optional) host will send responses on this channel. useful for automating protocol actions between agents. like acapy webhook
      short: a
      long: automation
      takes_value: true
      possible_values:
        - none
        - http
  - automationConfig:
      help: input for configuring automation. see docs for details.  its likely to be json format specific for type
      short: b
      long: automation-config
      takes_value: true


