name: yaml_app
version: "1.0"
about: an example using a .yaml file to build a CLI
author: Kevin K. <kbknapp@gmail.com>

# AppSettings can be defined as a list and are **not** ascii case sensitive
settings:
  - ArgRequiredElseHelp

# All Args must be defined in the 'args:' list where the name of the arg, is the
# key to a Hash object
args:
  # The name of this argument, is 'opt' which will be used to access the value
  # later in your Rust code
  - opt:
      help: defines IP and port the host will use to listen to request
      short: h
      long: host
      takes_value: true
