name: yaml_app
version: "1.0"
about: an example using a .yaml file to build a CLI
author: Kevin K. <kbknapp@gmail.com>

# AppSettings can be defined as a list and are **not** ascii case sensitive
settings:
  - ArgRequiredElseHelp

# All Args must be defined in the 'args:' list where the name of the arg, is the
# key to a Hash object
#
# ToThink():
#  1 once we support both agent and agency, will need input for which one
args:
  - host:
      help: ip/port host will use to listen to request such as 127.0.0.1:8000
      short: h
      long: host
      takes_value: true
  - role:
      help: agent or agency.
      short: r
      long: role
      takes_value: true
      possible_values:
          - agent
          - agency
  - walletType:
      help: wallet storage for agent
      short: w
      long: wallet
      takes_value: true
      possible_values:
        - basic
        - indy
