[package]
name = "aries-shared"
version = "0.1.0"
authors = ["tatmanblue <Matt.Raffel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# keep these in alphabetical order
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"